/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index" |
       "/pages-basic/badge/base" |
       "/pages-basic/badge/boundless" |
       "/pages-basic/badge/color" |
       "/pages-basic/badge/content" |
       "/pages-basic/badge/custom" |
       "/pages-basic/badge/hidden" |
       "/pages-basic/badge/placement" |
       "/pages-basic/badge/shape" |
       "/pages-basic/badge/size" |
       "/pages-basic/badge/standalone" |
       "/pages-basic/button/base" |
       "/pages-basic/button/color" |
       "/pages-basic/button/custom" |
       "/pages-basic/button/disabled" |
       "/pages-basic/button/full" |
       "/pages-basic/button/icon" |
       "/pages-basic/button/label" |
       "/pages-basic/button/loading" |
       "/pages-basic/button/radius" |
       "/pages-basic/button/size" |
       "/pages-basic/button/usage" |
       "/pages-basic/button/variant" |
       "/pages-basic/divider/base" |
       "/pages-basic/divider/color" |
       "/pages-basic/divider/dashed" |
       "/pages-basic/divider/hairline" |
       "/pages-basic/divider/position" |
       "/pages-basic/divider/text" |
       "/pages-basic/divider/thickness" |
       "/pages-basic/divider/vertical" |
       "/pages-basic/icon/base" |
       "/pages-basic/icon/color" |
       "/pages-basic/icon/name" |
       "/pages-basic/icon/size" |
       "/pages-basic/overlay/animation" |
       "/pages-basic/overlay/backdrop" |
       "/pages-basic/overlay/base" |
       "/pages-basic/overlay/controlled" |
       "/pages-basic/overlay/default-value" |
       "/pages-basic/overlay/dismissable" |
       "/pages-basic/overlay/lock-scroll" |
       "/pages-basic/overlay/placement" |
       "/pages-basic/overlay/z-index" |
       "/pages-basic/roller/base" |
       "/pages-basic/roller/controlled" |
       "/pages-basic/roller/custom" |
       "/pages-basic/roller/disabled" |
       "/pages-basic/roller/item-height" |
       "/pages-basic/roller/multiple" |
       "/pages-basic/roller/options" |
       "/pages-basic/roller/visible-count" |
       "/pages-form/checkbox/base" |
       "/pages-form/checkbox/color" |
       "/pages-form/checkbox/controlled" |
       "/pages-form/checkbox/disabled" |
       "/pages-form/checkbox/group-color" |
       "/pages-form/checkbox/group-controlled" |
       "/pages-form/checkbox/group-disabled" |
       "/pages-form/checkbox/group-size" |
       "/pages-form/checkbox/indeterminate" |
       "/pages-form/checkbox/label" |
       "/pages-form/checkbox/orientation" |
       "/pages-form/checkbox/size" |
       "/pages-form/checkbox/usage" |
       "/pages-form/checkbox/value" |
       "/pages-form/field/base" |
       "/pages-form/field/description" |
       "/pages-form/field/disabled" |
       "/pages-form/field/error" |
       "/pages-form/field/label-width" |
       "/pages-form/field/label" |
       "/pages-form/field/name" |
       "/pages-form/field/orientation" |
       "/pages-form/field/required" |
       "/pages-form/field/size" |
       "/pages-form/form/base" |
       "/pages-form/form/debounce-time" |
       "/pages-form/form/disabled" |
       "/pages-form/form/label-width" |
       "/pages-form/form/orientation" |
       "/pages-form/form/schema-arktype" |
       "/pages-form/form/schema-zod" |
       "/pages-form/form/size" |
       "/pages-form/form/submit" |
       "/pages-form/form/validate-on" |
       "/pages-form/form/values" |
       "/pages-form/input/base" |
       "/pages-form/input/clearable" |
       "/pages-form/input/controlled" |
       "/pages-form/input/counter" |
       "/pages-form/input/custom" |
       "/pages-form/input/disabled" |
       "/pages-form/input/icon" |
       "/pages-form/input/maxlength" |
       "/pages-form/input/password" |
       "/pages-form/input/placeholder" |
       "/pages-form/input/readonly" |
       "/pages-form/input/size" |
       "/pages-form/input/type" |
       "/pages-form/input/usage" |
       "/pages-form/number-input/base" |
       "/pages-form/number-input/disabled" |
       "/pages-form/number-input/formatter" |
       "/pages-form/number-input/min-max" |
       "/pages-form/number-input/placeholder" |
       "/pages-form/number-input/readonly" |
       "/pages-form/number-input/size" |
       "/pages-form/number-input/step-strictly" |
       "/pages-form/number-input/step" |
       "/pages-form/number-input/usage" |
       "/pages-form/picker/base" |
       "/pages-form/picker/cascade" |
       "/pages-form/picker/controlled" |
       "/pages-form/picker/custom-option" |
       "/pages-form/picker/disabled" |
       "/pages-form/picker/item-height" |
       "/pages-form/picker/multi-column" |
       "/pages-form/picker/transform" |
       "/pages-form/picker/visible-count" |
       "/pages-form/radio/base" |
       "/pages-form/radio/color" |
       "/pages-form/radio/disabled" |
       "/pages-form/radio/group-color" |
       "/pages-form/radio/group-controlled" |
       "/pages-form/radio/group-disabled" |
       "/pages-form/radio/group-size" |
       "/pages-form/radio/label" |
       "/pages-form/radio/orientation" |
       "/pages-form/radio/size" |
       "/pages-form/radio/value" |
       "/pages-form/slider/base" |
       "/pages-form/slider/color" |
       "/pages-form/slider/controlled" |
       "/pages-form/slider/disabled" |
       "/pages-form/slider/formatter" |
       "/pages-form/slider/min-max" |
       "/pages-form/slider/show-value" |
       "/pages-form/slider/size" |
       "/pages-form/slider/step" |
       "/pages-form/slider/usage" |
       "/pages-form/switch/base" |
       "/pages-form/switch/color" |
       "/pages-form/switch/controlled" |
       "/pages-form/switch/disabled" |
       "/pages-form/switch/icon" |
       "/pages-form/switch/loading" |
       "/pages-form/switch/readonly" |
       "/pages-form/switch/size" |
       "/pages-form/switch/usage" |
       "/pages-form/textarea/auto-height" |
       "/pages-form/textarea/base" |
       "/pages-form/textarea/clearable" |
       "/pages-form/textarea/controlled" |
       "/pages-form/textarea/disabled" |
       "/pages-form/textarea/maxlength" |
       "/pages-form/textarea/placeholder" |
       "/pages-form/textarea/readonly" |
       "/pages-form/textarea/show-count" |
       "/pages-form/textarea/size" |
       "/pages-form/textarea/usage" |
       "/pages-feedback/dialog/base" |
       "/pages-feedback/dialog/dismissable" |
       "/pages-feedback/dialog/long-content" |
       "/pages-feedback/spinner/base" |
       "/pages-feedback/spinner/color" |
       "/pages-feedback/spinner/size" |
       "/pages-feedback/spinner/variant" |
       "/pages-feedback/toast/backdrop" |
       "/pages-feedback/toast/base" |
       "/pages-feedback/toast/closable" |
       "/pages-feedback/toast/controlled" |
       "/pages-feedback/toast/custom" |
       "/pages-feedback/toast/duration" |
       "/pages-feedback/toast/icon" |
       "/pages-feedback/toast/message" |
       "/pages-feedback/toast/placement" |
       "/pages-feedback/toast/type" |
       "/pages-feedback/toast/z-index" |
       "/pages-design/colors/background" |
       "/pages-design/colors/border" |
       "/pages-design/colors/functional" |
       "/pages-design/colors/text";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
